jasypt:
   encryptor:
      password: ${jasyptpwd:secretkey}
      algorithm: PBEWithMD5AndDES

server:
   port: 8090
   servlet:
      context-path: /adn-brian-gomez
      session:
         timeout: 21600s

spring:
   datasource:
      type: com.zaxxer.hikari.HikariDataSource
      jdbcUrl: jdbc:mysql://prueba-concepto.mysql.database.azure.com:3306/adn?useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC
      username: brian@prueba-concepto
      password: Armenia2021
      hikari:
         poolName: pool
