jasypt:
   encryptor:
      password: ${jasyptpwd:secretkey}
      algorithm: PBEWithMD5AndDES

server:
   port: 8090
   servlet:
      context-path: /adn-brian-gomez
      session:
         timeout: 21600s

spring:
   datasource:
      type: com.zaxxer.hikari.HikariDataSource
      jdbcUrl: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_DATABASE}?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      username: ${DB_USER}
      password: '${DB_PASSWORD}'
      hikari:
         poolName: pool
