
package com.ceiba.infraestructura.superintendencia;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "TCRMServicesWebService", targetNamespace = "http://action.trm.services.generic.action.superfinanciera.nexura.sc.com.co/", wsdlLocation = "file:/D:/REPOSITORIOS/adn-brian-gomez-back/microservicio/src/main/resources/superintendencia.wsdl")
public class TCRMServicesWebService
    extends Service
{

    private final static URL TCRMSERVICESWEBSERVICE_WSDL_LOCATION;
    private final static WebServiceException TCRMSERVICESWEBSERVICE_EXCEPTION;
    private final static QName TCRMSERVICESWEBSERVICE_QNAME = new QName("http://action.trm.services.generic.action.superfinanciera.nexura.sc.com.co/", "TCRMServicesWebService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/D:/REPOSITORIOS/adn-brian-gomez-back/microservicio/src/main/resources/superintendencia.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        TCRMSERVICESWEBSERVICE_WSDL_LOCATION = url;
        TCRMSERVICESWEBSERVICE_EXCEPTION = e;
    }

    public TCRMServicesWebService() {
        super(__getWsdlLocation(), TCRMSERVICESWEBSERVICE_QNAME);
    }

    public TCRMServicesWebService(WebServiceFeature... features) {
        super(__getWsdlLocation(), TCRMSERVICESWEBSERVICE_QNAME, features);
    }

    public TCRMServicesWebService(URL wsdlLocation) {
        super(wsdlLocation, TCRMSERVICESWEBSERVICE_QNAME);
    }

    public TCRMServicesWebService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, TCRMSERVICESWEBSERVICE_QNAME, features);
    }

    public TCRMServicesWebService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TCRMServicesWebService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns TcrmServicesInterface
     */
    @WebEndpoint(name = "TcrmServicesInterfaceImplPort")
    public TcrmServicesInterface getTcrmServicesInterfaceImplPort() {
        return super.getPort(new QName("http://action.trm.services.generic.action.superfinanciera.nexura.sc.com.co/", "TcrmServicesInterfaceImplPort"), TcrmServicesInterface.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TcrmServicesInterface
     */
    @WebEndpoint(name = "TcrmServicesInterfaceImplPort")
    public TcrmServicesInterface getTcrmServicesInterfaceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://action.trm.services.generic.action.superfinanciera.nexura.sc.com.co/", "TcrmServicesInterfaceImplPort"), TcrmServicesInterface.class, features);
    }

    private static URL __getWsdlLocation() {
        if (TCRMSERVICESWEBSERVICE_EXCEPTION!= null) {
            throw TCRMSERVICESWEBSERVICE_EXCEPTION;
        }
        return TCRMSERVICESWEBSERVICE_WSDL_LOCATION;
    }

}
